/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.travelagency.sandeep.ui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author sande
 */
public class Login_ui extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login_ui.class.getName());

    /**
     * Creates new form Login_ui
     */
    public Login_ui() {
        initComponents();
//        username.setOpaque(false);            // removes fill background
//        username.setBackground(new Color(0, 0, 0, 0)); // fully transparent background
//        username.setBorder(null);             // optional: remove border
//        username.setForeground(Color.BLACK);  // text color
//        username.setCaretColor(Color.WHITE);  // typing cursor color
//        password.setOpaque(false);            // removes fill background
//        password.setBackground(new Color(0, 0, 0, 0)); // fully transparent background
//        password.setBorder(null);             // optional: remove border
//        password.setForeground(Color.WHITE);  // text color
//        password.setCaretColor(Color.WHITE);  // typing cursor color
//
//// make button transparent
        jloginButton.setOpaque(false);
        jloginButton.setContentAreaFilled(false);  // removes background fill
        jloginButton.setBorderPainted(false);      // removes border
        jloginButton.setFocusPainted(false);       // removes focus outline
        jloginButton.setForeground(Color.WHITE);   // text color
        jloginButton.setFont(new Font("Segoe UI", Font.BOLD, 14));

        jshowButton.setOpaque(false);
        jshowButton.setContentAreaFilled(false);  // removes background fill
        jshowButton.setBorderPainted(false);      // removes border
        jshowButton.setFocusPainted(false);       // removes focus outline
        jshowButton.setForeground(Color.WHITE);   // text color
        jshowButton.setFont(new Font("Segoe UI", Font.BOLD, 14));

        jloginUserButton.setOpaque(false);
        jloginUserButton.setContentAreaFilled(false);  // removes background fill
        jloginUserButton.setBorderPainted(false);      // removes border
        jloginUserButton.setFocusPainted(false);       // removes focus outline
        jloginUserButton.setForeground(Color.WHITE);   // text color
        jloginUserButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jloginButton = new javax.swing.JButton();
        jshowButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jloginUserButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 85, -1));

        username.setBackground(new java.awt.Color(102, 102, 102));
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 261, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 101, 30));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("jPasswordField1");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 261, 34));

        jloginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jloginButton.setForeground(new java.awt.Color(0, 0, 0));
        jloginButton.setText("Login");
        jloginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jloginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 90, -1));

        jshowButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jshowButton.setForeground(new java.awt.Color(0, 0, 0));
        jshowButton.setText("Show Password");
        jshowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jshowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("OR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jloginUserButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jloginUserButton.setForeground(new java.awt.Color(0, 0, 0));
        jloginUserButton.setText("Login as a User");
        jloginUserButton.setBorder(null);
        jloginUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginUserButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jloginUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 190, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\image.jpg")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginButtonActionPerformed
        String user = username.getText();
        String pass = new String(password.getPassword());

        com.travelagency.sandeep.main.LoginInfo loginInfo = new com.travelagency.sandeep.main.LoginInfo();

        if (loginInfo.getLoginInfo().containsKey(user)) {
            if (loginInfo.getLoginInfo().get(user).equals(pass)) {
                //javax.swing.JOptionPane.showMessageDialog(this, "Login Successful!");
                this.dispose(); // close login frame
                new Admin_ui().setVisible(true); // open admin panel
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Password!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username!");
        }
    }//GEN-LAST:event_jloginButtonActionPerformed

    private void jshowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowButtonActionPerformed
        if (password.getEchoChar() == '\u0000') {
            // Password is visible → hide it
            password.setEchoChar('*');
            jshowButton.setText("Show Password");
        } else {
            // Password is hidden → show it
            password.setEchoChar('\u0000');
            jshowButton.setText("Hide Password");
        }
    }//GEN-LAST:event_jshowButtonActionPerformed

    private void jloginUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginUserButtonActionPerformed
        this.dispose(); // Close the login window
        new User_ui().setVisible(true);
    }//GEN-LAST:event_jloginUserButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_ui().setVisible(true));
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jloginButton;
    private javax.swing.JButton jloginUserButton;
    private javax.swing.JButton jshowButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
