/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.travelagency.sandeep.ui;

import com.travelagency.service.BookingService;
import com.travelagency.service.PackageService;
import com.travelagency.model.PackageModel;
import com.travelagency.model.BookingModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author sande
 */
public class User_ui extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_ui.class.getName());

    /**
     * Creates new form User_ui
     */
    public User_ui() {
        initComponents();
    }
    private final PackageService packageService = new PackageService();
    private final BookingService bookingService = new BookingService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewPackage = new javax.swing.JButton();
        bookPackage = new javax.swing.JButton();
        cancelBooking = new javax.swing.JButton();
        viewBooking = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome To Our Travel Agency");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("From Peaks to Valleys, We Guide Your Nepalese Odyssey!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 26));

        viewPackage.setBackground(new java.awt.Color(102, 102, 102));
        viewPackage.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        viewPackage.setText("1. View Packages");
        viewPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPackageActionPerformed(evt);
            }
        });
        jPanel1.add(viewPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 340, 30));

        bookPackage.setBackground(new java.awt.Color(102, 102, 102));
        bookPackage.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        bookPackage.setText("2. Book your Packages");
        bookPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPackageActionPerformed(evt);
            }
        });
        jPanel1.add(bookPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 340, 28));

        cancelBooking.setBackground(new java.awt.Color(102, 102, 102));
        cancelBooking.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        cancelBooking.setText("3. Cancel your Booking");
        cancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 340, 28));

        viewBooking.setBackground(new java.awt.Color(102, 102, 102));
        viewBooking.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        viewBooking.setText("4. View your Bookings");
        viewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingActionPerformed(evt);
            }
        });
        jPanel1.add(viewBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 340, 33));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Thank you for traveling with us— Namaste & see you soon!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\travelbg.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 630, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Package Id", "Package Name", "Duration", "Price"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 0, 580, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPackageActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Package ID", "Name", "Duration", "Price"});
        for (PackageModel pkg : packageService.getAllPackages()) {
            model.addRow(new Object[]{pkg.getId(), pkg.getName(), pkg.getDuration(), pkg.getPrice()});
        }
    }//GEN-LAST:event_viewPackageActionPerformed

    private void bookPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPackageActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter your name:");
        if (name == null) {
            return;
        }
        String phone = JOptionPane.showInputDialog(this, "Enter your phone:");
        if (phone == null) {
            return;
        }

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a package first!");
            return;
        }
        int packageId = (int) jTable1.getValueAt(selectedRow, 0);
        bookingService.bookPackage(name, phone, packageId);
        JOptionPane.showMessageDialog(this, "Booking successful!");
    }//GEN-LAST:event_bookPackageActionPerformed

    private void cancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingActionPerformed
        String bookingIdStr = JOptionPane.showInputDialog(this, "Enter Booking ID to cancel:");
        if (bookingIdStr == null) {
            return;
        }
        try {
            int bookingId = Integer.parseInt(bookingIdStr);
            bookingService.cancelBooking(bookingId);
            JOptionPane.showMessageDialog(this, "Booking cancelled successfully!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Booking ID");
        }
    }//GEN-LAST:event_cancelBookingActionPerformed

    private void viewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookingActionPerformed
        String phone = JOptionPane.showInputDialog(this, "Enter your phone to view bookings:");
        if (phone == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Booking ID", "Package Name", "Duration", "Price"});
        for (BookingModel booking : bookingService.getUserBookings(phone)) {
            model.addRow(new Object[]{booking.getBookingId(), booking.getPackageName(), booking.getDuration(), booking.getPrice()});
        }
    }//GEN-LAST:event_viewBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_ui().setVisible(true));        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookPackage;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton viewBooking;
    private javax.swing.JButton viewPackage;
    // End of variables declaration//GEN-END:variables
}
